### PR TITLE
Updating bits to OData 7.2

### PR DESCRIPTION
**Pull request by robertmclaws**
- Upgrade everything to the latest NuGet packages, (Including OData 7.2, which supports .NET Standard).
- Fix bug in Restier controllers where it SwaggerRouteStrategy did not account for unbounded functions.
- Temporarily replace Microsoft's Restier NuGets with AdvancedREI's newer fork (tests only).
- Fix unit tests that were relying on relative mapping instead of using absolute locations.
- Temporarily disables runtime code contracts (causing issues in IIS10).
- Incremented the major build on the NuGet package (because OData 7.2 may have breaking changes).
- Added support for the $apply entity set option in OData v4 (#147)

### CODE REVIEW

**Comment by robertmclaws** [comment]
Hey Richard, hope you are well. Starting to use this library quite a bit, so I thought I'd contribute back some updates. Hope you find them useful. lemme know if you have any questions. Thanks!

**Comment by rbeauchamp** [comment]
Hi @robertmclaws doing okay thanks! Hope all is well with you. Thank you for working on these upgrades.

> Temporarily replace Microsoft's Restier NuGets with AdvancedREI's newer fork

Why did you need to do this? Would rather not take a dependency on AdvancedREI libraries over MS libraries.

> Temporarily disables runtime code contracts (causing issues in IIS10).

To ensure quality, I'd rather not disable code contract checks. Is there a work around? or maybe the question is how 'temporary' is this? :-)

Also, looks like there are conflicts after merging an earlier PR.

**Comment by robertmclaws** [comment]
OK, so I fixed the conflicts. Here's the deal:

- I switched to my fork of Restier because Microsoft hasn't done anything with their version in a while, and their version is not yet compatible with OData 7.X. My version is. My version also fixes a number of bugs that they haven't gotten to yet. Since it's only for the tests themselves, it shouldn't affect anything major. Just makes sure you're testing and working on the newer stuff (and I have a whole pipeline running on 7.X that I needed all this to work for.)

- I disabled the runtime code contracts because I honestly have no idea how they work, and they were getting in my way. My M.O. was to disable them, ship a version on my internal NuGet, and then you could re-enable it after you accept my PR. Since you probably know more about it than I do.

HTH!

**Comment by rbeauchamp** [comment]
@robertmclaws thanks for the explanation. let's do this: since your changes are in beta, i created an issue rbeauchamp/Swashbuckle.OData#150 and i'm updating your PR to merge into the associated feature branch https://github.com/rbeauchamp/Swashbuckle.OData/tree/feature/%23150. From that branch I'll build and upload the nuget package.

BTW, are code contracts not working on your machine because you haven't installed it? See https://github.com/rbeauchamp/Swashbuckle.OData/tree/feature/%23150#development

**Pull request merged**
