### PR TITLE
upgrade to nunit 3

### PR DESCRIPTION
**Pull request by bigred8982**

### CODE REVIEW

**Comment by bigred8982** [comment]
Looks like this change may have caused some issues with the automated testing through AppVeyor.

**Comment by rbeauchamp** [comment]
right, it only supports v2.x

**Comment by bigred8982** [comment]
gotcha. Ok, we should kill this pull request then.

**Comment by bigred8982** [comment]
@rbeauchamp There is a way to upgrade AppVeyor to use nunit 3.0 if you're interested in doing so.

https://gist.github.com/FeodorFitsner/27ebfd99204f2d8e1cc4

**Comment by rbeauchamp** [comment]
oh cool. thanks! I'm fine with upgrading to v3.

**Pull request closed without merging**
