### PR TITLE
Add support for xmlComments and for using swaggerResponseAttributes a…

### PR DESCRIPTION
**Pull request by cibergarri**
…nd OdataResponse and its subclasses on nested resources. Allow ODataResponse metadata property to be overrided. Creaete ODataListResponse for Ienumerable Responses with Odata properties

### CODE REVIEW

**Comment by rbeauchamp** [comment]
hey @cibergarri, thank you for these updates. Looks like 2 of the test are failing.

**Comment by cibergarri** [comment]
Mmmmmm... they are working on my machine.
image

**Comment by cibergarri** [comment]
Oops, some last minute changes, sorry.  Fixed.

**Comment by cibergarri** [comment]
Hi Richard!!
First of all, thanks for accepting my PR!

Since I have contributed to this project, shouldn't I appear in the contributors list?
It's the very first time I colaborate in an open source project and I don't know exactly how it works ... But it would make me happy :)

**Comment by rbeauchamp** [comment]
Hi @cibergarri, thank you for the PRs! I've made a point of changing the
author and the copyright to include 'and the Swashbuckle.OData
contributors'. I don't currently have a contributors list but would be
happy to include one: can you point me to an open-source project that does
a good job including or displaying and contributors list?

**Comment by cibergarri** [comment]
Oh! I was just referring to the github contributors list!
But don't worry, it is not importante at all.

Obtener Outlook para Android<https://aka.ms/ghei36>


________________________________

**Comment by rbeauchamp** [comment]
@cibergarri It is strange that you are not showing up on the contributors list. This is something automatically handled by github. When you look here: https://github.com/rbeauchamp/Swashbuckle.OData/commits/master I see your commits but don't see your picture and there is no link on your username as there is with other contributors. ????

**Comment by cibergarri** [comment]
I think it's because of someone of the reasons mentioned here:
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

Thanks anyway!

________________________________

**Pull request merged**
