### PR TITLE
Issues/64

### PR DESCRIPTION
**Pull request by bigred8982**

### CODE REVIEW

**Comment by bigred8982** [comment]
Looks like there is a merge issue. Is there something I can do to help resolve this?

**Comment by rbeauchamp** [comment]
maybe pull and merge from master back into your fork/branch?

**Comment by rbeauchamp** [comment]
On this page, in the desktop view, I see command line instructions to resolve the conflicts.

**Comment by bigred8982** [comment]
I can try that. I'll probably need to delete this pull request and create a
new one. I'll fuss with it later today.

**Comment by rbeauchamp** [comment]
Sure. As I understand the pull request will 'auto' update as you update your branch...

**Comment by bigred8982** [comment]
I updated the pull request by merging your master into the branch. Please let me know if there are any code changes or whatnot you'd like me to change.

**Comment by bigred8982** [comment]
For issue #64

**Pull request merged**
