### PR TITLE
Several enhancements to Swashbuckle.OData 

### PR DESCRIPTION
**Pull request by ysmoradi**
Summary:
______________________________
I've updated nunit nuget packages + I've added NUnit3TestAdapeter to make tests runnable directly in visual studio. (VS 2017 in my case)
______________________________
WebAPI/OData allows us to define odata actions with parameters of type other than ODataActionParameters type. For example:
```csharp
public class EmailData
{
    public virtual string Title { get; set; }
    // , ...
}

public class EmailController : ODataController
{
    // action
    public async SendEmail(EmailData data)
    {
    }
}
```
So, I committed [MapToODataActionParameter won't raise an exception when odata action has no odata action parameter](https://github.com/rbeauchamp/Swashbuckle.OData/commit/582666c12fa8c071089f930b0e7c85a9c768a65b) because it's not a must have really.
______________________________
We might develop custom enable query attribute for several reasons. For example, I run queries async in my own customized action filter + We might add EnableQuery globally or at class level instead of action level. So I committed [Add support for global level enable query action filter](https://github.com/rbeauchamp/Swashbuckle.OData/commit/b0ac16f4c09581ad1da9bf5fec75622df4278247) This checks if any EnableQuery exists action's filter pipeline. This includes EnableQuery on action itself, on its class or global level of web api action filters. This accepts that only if return type of action is suitable for odata queries such as $filter, so it checks the return type to be a enumerable type. This is not a breaking change, as **previews behavior exists untouched**.
______________________________
[Bit framework](https://docs.bit-framework.com/) is a full stack C#/TypeScript/JavaScript framework which allows you to develop api/odata/background job/messaging on top of asp.net core and asp.net using owin abstractions. It has offline support for both Xamarin & Web clients and it has support for RAD components. It's open source and free to use with MIT license. We're very happy with what you've done in this amazing project (Swashbuckle.OData) and we'd like to use this project in our full stack framework. If you accept this PR, we can continue our contribution alongside you to make it even better.
**Let us know if any improvements can be done to this PR.**
Thanks for what you've done for us. Bit team.

### CODE REVIEW

**Comment by ysmoradi** [comment]
Note: there is another problem with owin branching, we may talk about that later. For now, let's focus on this PR.

**Comment by ysmoradi** [comment]
[TypeHelper.IsCollection](https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData/Descriptions/TypeHelper.cs#L43) should return false when null is passed to it. For example when we're using that method to determinate the return type of odata action is collection type or not, while the action's return type is void, so our return type would be null.
This method had no problem before, because it was called [inside a if in EnableQueryFilter.cs file](https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData/EnableQueryFilter.cs#L25).

**Comment by 9Rune5** [comment]
Does this solve issue https://github.com/rbeauchamp/Swashbuckle.OData/issues/86?

**Comment by ysmoradi** [comment]
@9Rune5 it solves this issue + lots of other issues

**Comment by 9Rune5** [comment]
It got me a little further, now I get this instead:
```
[Window Title]
iisexpress.exe - Assumption failed.

[Main Instruction]
iisexpress.exe - Assumption failed.

[Content]
Description: Assumption failed.

[Expanded Information]
Stack Trace:
   at System.Diagnostics.Contracts.Contract.Assume(Boolean condition)
   at Swashbuckle.OData.Descriptions.MapToODataActionParameter.Map(Parameter swaggerParameter, Int32 parameterIndex, HttpActionDescriptor actionDescriptor) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\MapToODataActionParameter.cs:line 19
   at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.<>c__DisplayClass5_0.<GetHttpParameterDescriptor>b__0(IParameterMapper mapper) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\SwaggerOperationMapper.cs:line 72
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.GetHttpParameterDescriptor(Parameter parameter, Int32 index, HttpActionDescriptor actionDescriptor) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\SwaggerOperationMapper.cs:line 71
   at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.GetParameterDescription(Parameter parameter, Int32 index, HttpActionDescriptor actionDescriptor) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\SwaggerOperationMapper.cs:line 53
   at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.<>c__DisplayClass3_0.<CreateParameterDescriptions>b__0(Parameter parameter, Int32 index) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\SwaggerOperationMapper.cs:line 43
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.CreateParameterDescriptions(Operation operation, HttpActionDescriptor actionDescriptor) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\SwaggerOperationMapper.cs:line 42
   at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.Map(ODataActionDescriptor oDataActionDescriptor) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\SwaggerOperationMapper.cs:line 29
   at Swashbuckle.OData.Descriptions.ODataApiExplorer.<>c__DisplayClass7_0.<GetApiDescriptions>b__2(IODataActionDescriptorMapper mapper) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\ODataApiExplorer.cs:line 49
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Swashbuckle.OData.Descriptions.ODataApiExplorer.<GetApiDescriptions>b__7_1(ODataActionDescriptor oDataActionDescriptor) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\ODataApiExplorer.cs:line 49
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.OData.CollectionExtentions.ToCollection[T](IEnumerable`1 source) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\CollectionExtentions.cs:line 77
   at Swashbuckle.OData.Descriptions.ODataApiExplorer.GetApiDescriptions() in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\ODataApiExplorer.cs:line 43
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Swashbuckle.OData.Descriptions.ODataApiExplorer.get_ApiDescriptions() in C:\repos\Swashbuckle.OData\Swashbuckle.OData\Descriptions\ODataApiExplorer.cs:line 39
   at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion) in C:\repos\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 319
   at Swashbuckle.OData.ODataSwaggerProvider.Generate
```

I have always been told that writing docs is hard. :)

**Comment by 9Rune5** [comment]
FWIW, the action causing me problems is declared as:
 ```
       [HttpPost]
        public async Task<IHttpActionResult> Ban([FromODataUri] int key)
```
Which is just a simple `.Action("Ban"); `off my entity.

**Comment by rbeauchamp** [comment]
@ysmoradi thank you so much for this pull request. sorry for the delay in merging it. will do so now...

**Comment by 9Rune5** [comment]
Scratch that, I might be looking at the wrong branch.

**Comment by 9Rune5** [comment]
@rbeauchamp How long until a new NuGet package?

**Comment by ysmoradi** [comment]
@rbeauchamp Thanks ;)

**Comment by rbeauchamp** [comment]
Nuget package is now available at https://www.nuget.org/packages/Swashbuckle.OData/4.0.0-beta2

**Pull request merged**
